feat: backup and restore file storage using rclone

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,6 +1,9 @@
 x-database-image: &database-image
   image: postgis/postgis:${POSTGRES_VERSION:-16-master}
 
+x-file-storage-image: &file-storage-image
+  image: rclone/rclone:${RCLONE_VERSION:-1.68}
+
 services:
   app:
     image: dhis2/core:${DHIS2_VERSION:-42}
@@ -123,20 +126,6 @@ services:
       database:
         condition: service_healthy
 
-  backup-file-storage:
-    profiles:
-      - backup
-    image: busybox:1.37.0
-    volumes:
-      - dhis2:/opt/dhis2/
-      - ./backups:/backups
-    entrypoint: >
-      /bin/sh -c "
-        set -o errexit
-
-        tar --create --verbose --gzip --file /backups/$$BACKUP_TIMESTAMP.tar.gz --directory /opt/dhis2/files .
-      "
-
   restore-database:
     profiles:
       - restore
@@ -188,34 +177,55 @@ services:
       database:
         condition: service_healthy
 
-  restore-file-storage:
+  backup-file-storage:
     profiles:
-      - restore
-    image: busybox:1.37.0
+      - backup
+    <<: *file-storage-image
     volumes:
       - dhis2:/opt/dhis2/
       - ./backups:/backups
     environment:
-      FILE_STORAGE_RESTORE_FILE: ${FILE_STORAGE_RESTORE_FILE}
+      BACKUP_TIMESTAMP: ${BACKUP_TIMESTAMP}
+      BACKUP_SOURCE_PATH: ${BACKUP_SOURCE_PATH:-/opt/dhis2/files}
+    entrypoint: >
+      /bin/sh -c "
+        set -o errexit
+      
+        rclone copy \"$$BACKUP_SOURCE_PATH\" \"/backups/file-storage-$${BACKUP_TIMESTAMP}\" --verbose --create-empty-src-dirs
+
+        echo 'File storage backup completed successfully'
+      "
+
+  restore-file-storage:
+    profiles:
+      - restore
+    <<: *file-storage-image
+    volumes:
+      - dhis2:/opt/dhis2/
+      - ./backups:/backups
+    environment:
+      FILE_STORAGE_RESTORE_SOURCE_DIR: ${FILE_STORAGE_RESTORE_SOURCE_DIR}
+      RESTORE_DESTINATION_PATH: ${RESTORE_DESTINATION_PATH:-/opt/dhis2/files}
     entrypoint: >
       /bin/sh -c "
         set -o errexit
 
-        if [ -z \"$$FILE_STORAGE_RESTORE_FILE\" ]; then
-          echo \"Error: FILE_STORAGE_RESTORE_FILE environment variable must be set\"
+        if [ -z \"$$FILE_STORAGE_RESTORE_SOURCE_DIR\" ]; then
+          echo 'Error: FILE_STORAGE_RESTORE_SOURCE_DIR environment variable must be set'
           exit 1
         fi
-      
-        if [ ! -f \"/backups/$$FILE_STORAGE_RESTORE_FILE\" ]; then
-          echo \"Error: Restore file /backups/$$FILE_STORAGE_RESTORE_FILE not found\"
+
+        # Add traingling slash to ensure content of the folder is copied rather than the folder itself
+        SRC=/backups/$$FILE_STORAGE_RESTORE_SOURCE_DIR/
+
+        if [ ! -d \"$$SRC\" ]; then
+          echo \"Error: Restore directory $$SRC not found\"
           exit 1
         fi
-      
-        echo \"Restoring file storage from $$FILE_STORAGE_RESTORE_FILE\"
-      
-        tar --extract --verbose --gzip --file /backups/$$FILE_STORAGE_RESTORE_FILE --directory /opt/dhis2/files
-      
-        echo \"File storage restore completed successfully\"
+
+        rclone copy \"$$SRC\" \"$$RESTORE_DESTINATION_PATH\" --verbose --create-empty-src-dirs
+
+        echo 'File storage restore completed successfully'
       "
 
 volumes:
